version: "2"
run:
  go: 1.24.0
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - goheader
    - gomoddirectives
    - goprintffuncname
    - gosmopolitan
    - grouper
    - importas
    - interfacebloat
    - loggercheck
    - makezero
    - mirror
    - misspell
    - nilerr
    - nilnil
    - noctx
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tagalign
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    revive:
      rules:
        - name: var-naming
          disabled: true
    staticcheck:
      checks:
        - all
        - '-SA1019'
        - '-ST1003'
        - '-QF1008'
        - '-QF1003'
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
        source: ^func Test
      - linters:
          - dupl
        path: (.+)_test\.go$
      - linters:
          - dupl
        path: consumer/
      - linters:
          - dupl
        path: scan/
      - linters:
          - nilnil
        path: (.+)_test\.go$
      - linters:
          - goconst
        path: (.+)_test\.go$
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
