{
 "title": "DoE-Hunter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Server Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backend",
   "type": "stat",
   "description": "Shows whether backend server is up.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    sum without() (up{job=\"backend\", instance=\"vm-dnsscan-db-1:9090\"})\n      or\n    (0 * sum_over_time(up{job=\"backend\", instance=\"vm-dnsscan-db-1:9090\"}[7d]))\n  )[7d:5m]\n)",
     "legendFormat": "node_exporter"
    },
    {
     "expr": "avg_over_time(\n  (\n    sum without() (up{job=\"backend\", instance=\"vm-dnsscan-db-1:9080\"})\n      or\n    (0 * sum_over_time(up{job=\"backend\", instance=\"vm-dnsscan-db-1:9080\"}[7d]))\n  )[7d:5m]\n)",
     "legendFormat": "cAdvisor"
    },
    {
     "expr": "avg_over_time(\n  (\n    sum without() (up{job=\"backend\", instance=\"vm-dnsscan-db-1:9070\"})\n      or\n    (0 * sum_over_time(up{job=\"backend\", instance=\"vm-dnsscan-db-1:9070\"}[7d]))\n  )[7d:5m]\n)",
     "legendFormat": "dockerd"
    }
   ]
  },
  {
   "title": "Worker-1",
   "type": "stat",
   "description": "Shows whether worker-1 server is up.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    sum without() (up{job=\"worker-1\", instance=\"vm-dnsscan-worker-1:9090\"})\n      or\n    (0 * sum_over_time(up{job=\"worker-1\", instance=\"vm-dnsscan-worker-1:9090\"}[7d]))\n  )[7d:5m]\n)",
     "legendFormat": "node_exporter"
    },
    {
     "expr": "avg_over_time(\n  (\n    sum without() (up{job=\"worker-1\", instance=\"vm-dnsscan-worker-1:9080\"})\n      or\n    (0 * sum_over_time(up{job=\"worker-1\", instance=\"vm-dnsscan-worker-1:9080\"}[7d]))\n  )[7d:5m]\n)",
     "legendFormat": "cAdvisor"
    },
    {
     "expr": "avg_over_time(\n  (\n    sum without() (up{job=\"worker-1\", instance=\"vm-dnsscan-worker-1:9070\"})\n      or\n    (0 * sum_over_time(up{job=\"worker-1\", instance=\"vm-dnsscan-worker-1:9070\"}[7d]))\n  )[7d:5m]\n)",
     "legendFormat": "dockerd"
    }
   ]
  },
  {
   "title": "Worker-2",
   "type": "stat",
   "description": "Shows whether worker-2 server is up.",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    sum without() (up{job=\"worker-2\", instance=\"vm-dnsscan-worker-2:9090\"})\n      or\n    (0 * sum_over_time(up{job=\"worker-2\", instance=\"vm-dnsscan-worker-2:9090\"}[7d]))\n  )[7d:5m]\n)",
     "legendFormat": "node_exporter"
    },
    {
     "expr": "avg_over_time(\n  (\n    sum without() (up{job=\"worker-2\", instance=\"vm-dnsscan-worker-2:9080\"})\n      or\n    (0 * sum_over_time(up{job=\"worker-2\", instance=\"vm-dnsscan-worker-2:9080\"}[7d]))\n  )[7d:5m]\n)",
     "legendFormat": "cAdvisor"
    },
    {
     "expr": "avg_over_time(\n  (\n    sum without() (up{job=\"worker-2\", instance=\"vm-dnsscan-worker-2:9070\"})\n      or\n    (0 * sum_over_time(up{job=\"worker-2\", instance=\"vm-dnsscan-worker-2:9070\"}[7d]))\n  )[7d:5m]\n)",
     "legendFormat": "dockerd"
    }
   ]
  },
  {
   "title": "Monitoring",
   "type": "stat",
   "description": "Shows whether monitoring server is up.",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    sum without() (up{job=\"monitoring\", instance=\"vm-dnsscan-monitoring-1:9095\"})\n      or\n    (0 * sum_over_time(up{job=\"monitoring\", instance=\"vm-dnsscan-monitoring-1:9095\"}[7d]))\n  )[7d:5m]\n)",
     "legendFormat": "node_exporter"
    },
    {
     "expr": "avg_over_time(\n  (\n    sum without() (up{job=\"monitoring\", instance=\"vm-dnsscan-monitoring-1:9080\"})\n      or\n    (0 * sum_over_time(up{job=\"monitoring\", instance=\"vm-dnsscan-monitoring-1:9080\"}[7d]))\n  )[7d:5m]\n)",
     "legendFormat": "cAdvisor"
    },
    {
     "expr": "avg_over_time(\n  (\n    sum without() (up{job=\"monitoring\", instance=\"vm-dnsscan-monitoring-1:9070\"})\n      or\n    (0 * sum_over_time(up{job=\"monitoring\", instance=\"vm-dnsscan-monitoring-1:9070\"}[7d]))\n  )[7d:5m]\n)",
     "legendFormat": "dockerd"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (mode,cpu) (\n  1 - rate(node_cpu_seconds_total{mode=\"idle\", instance=\"vm-dnsscan-db-1:9090\", job=\"backend\"}[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (mode,cpu) (\n  1 - rate(node_cpu_seconds_total{mode=\"idle\", instance=\"vm-dnsscan-worker-1:9090\", job=\"worker-1\"}[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (mode,cpu) (\n  1 - rate(node_cpu_seconds_total{mode=\"idle\", instance=\"vm-dnsscan-worker-2:9090\", job=\"worker-2\"}[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (mode,cpu) (\n  1 - rate(node_cpu_seconds_total{mode=\"idle\", instance=\"vm-dnsscan-monitoring-1:9095\", job=\"monitoring\"}[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mem Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"vm-dnsscan-db-1:9090\"}-node_memory_MemFree_bytes{instance=\"vm-dnsscan-db-1:9090\"})/node_memory_MemTotal_bytes{instance=\"vm-dnsscan-db-1:9090\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Mem Used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"vm-dnsscan-db-1:9090\"}-node_memory_MemFree_bytes{instance=\"vm-dnsscan-db-1:9090\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Mem Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"vm-dnsscan-worker-1:9090\"}-node_memory_MemFree_bytes{instance=\"vm-dnsscan-worker-1:9090\"})/node_memory_MemTotal_bytes{instance=\"vm-dnsscan-worker-1:9090\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Mem Used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"vm-dnsscan-worker-1:9090\"}-node_memory_MemFree_bytes{instance=\"vm-dnsscan-worker-1:9090\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Mem Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"vm-dnsscan-worker-2:9090\"}-node_memory_MemFree_bytes{instance=\"vm-dnsscan-worker-2:9090\"})/node_memory_MemTotal_bytes{instance=\"vm-dnsscan-worker-2:9090\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Mem Used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"vm-dnsscan-worker-2:9090\"}-node_memory_MemFree_bytes{instance=\"vm-dnsscan-worker-2:9090\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Mem Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"vm-dnsscan-monitoring-1:9095\"}-node_memory_MemFree_bytes{instance=\"vm-dnsscan-monitoring-1:9095\"})/node_memory_MemTotal_bytes{instance=\"vm-dnsscan-monitoring-1:9095\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Mem Avail",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"monitoring\"}-node_memory_MemFree_bytes{job=\"monitoring\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Mem Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"vm-dnsscan-db-1:9090\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Mem Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"vm-dnsscan-worker-1:9090\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Mem Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"vm-dnsscan-worker-2:9090\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Mem Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"monitoring\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"backend\"}",
     "legendFormat": "Free Mem"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"worker-1\"}",
     "legendFormat": "Free Mem"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"worker-2\"}",
     "legendFormat": "Free Mem"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"monitoring\"}",
     "legendFormat": "Free Mem"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"backend\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"backend\"})",
     "legendFormat": "/"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/db\",fstype!=\"rootfs\",job=\"backend\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/db\",fstype!=\"rootfs\",job=\"backend\"})",
     "legendFormat": "/db"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"worker-1\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"worker-1\"})",
     "legendFormat": "/"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"worker-2\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"worker-2\"})",
     "legendFormat": "/"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"monitoring\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"monitoring\"})",
     "legendFormat": "/"
    }
   ]
  },
  { "title": "Network Worker 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Internal Network Worker 1",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{job=\"worker-1\", device=\"enp3s0\"}[1m])",
     "legendFormat": "Recieved"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{job=\"worker-1\", device=\"enp3s0\"}[1m])",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "External Network Worker 1",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{job=\"worker-1\", device=\"enp4s0\"}[1m])",
     "legendFormat": "Recieved"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{job=\"worker-1\", device=\"enp4s0\"}[1m])",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Internal Network Packet Drops Worker 1",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_drop_total{job=\"worker-1\", device=\"enp3s0\"}[5m]))",
     "legendFormat": "Received Drop"
    },
    {
     "expr": "sum(rate(node_network_transmit_drop_total{job=\"worker-1\", device=\"enp3s0\"}[5m]))",
     "legendFormat": "Sent Drop"
    }
   ]
  },
  {
   "title": "External Network Packet Drops Worker 1",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 29 },
   "targets": [
    {
     "expr": "rate(node_network_receive_drop_total{job=\"worker-1\", device=\"enp4s0\"}[1m])",
     "legendFormat": "Received Drop"
    },
    {
     "expr": "rate(node_network_transmit_drop_total{job=\"worker-1\", device=\"enp4s0\"}[1m])",
     "legendFormat": "Sent Drop"
    }
   ]
  },
  { "title": "Network Worker 2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Internal Network Worker 2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{job=\"worker-2\", device=\"enp4s0\"}[1m])",
     "legendFormat": "Recieved"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{job=\"worker-2\", device=\"enp4s0\"}[1m])",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "External Network Worker 2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{job=\"worker-2\", device=\"enp3s0\"}[1m])",
     "legendFormat": "Recieved"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{job=\"worker-2\", device=\"enp3s0\"}[1m])",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Internal Network Packet Drops Worker 2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_drop_total{job=\"worker-2\", device=\"enp4s0\"}[5m]))",
     "legendFormat": "Received Drop"
    },
    {
     "expr": "sum(rate(node_network_transmit_drop_total{job=\"worker-2\", device=\"enp4s0\"}[5m]))",
     "legendFormat": "Sent Drop"
    }
   ]
  },
  {
   "title": "External Network Packet Drops Worker 2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_drop_total{job=\"worker-2\", device=\"enp3s0\"}[5m]))",
     "legendFormat": "Received Drop"
    },
    {
     "expr": "sum(rate(node_network_transmit_drop_total{job=\"worker-2\", device=\"enp3s0\"}[5m]))",
     "legendFormat": "Sent Drop"
    }
   ]
  },
  { "title": "Network Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Internal Network Backend",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{job=\"backend\", device=\"enp3s0\"}[1m])",
     "legendFormat": "Recieved"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{job=\"backend\", device=\"enp3s0\"}[1m])",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Internal Network Monitoring",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{job=\"monitoring\", device=\"enp3s0\"}[1m])",
     "legendFormat": "Recieved"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{job=\"monitoring\", device=\"enp3s0\"}[1m])",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Docker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Backend Containers",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{job=\"backend\", state=\"running\"}",
     "legendFormat": "Up"
    },
    {
     "expr": "engine_daemon_container_states_containers{job=\"backend\", state=\"stopped\"}",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Monitoring Containers",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{job=\"monitoring\", state=\"running\"}",
     "legendFormat": "Up"
    },
    {
     "expr": "engine_daemon_container_states_containers{job=\"monitoring\", state=\"stopped\"}",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Worker 1 Containers",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{job=\"worker-1\", state=\"running\"}",
     "legendFormat": "Up"
    },
    {
     "expr": "engine_daemon_container_states_containers{job=\"worker-1\", state=\"stopped\"}",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Worker 2 Containers",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{job=\"worker-2\", state=\"running\"}",
     "legendFormat": "Up"
    },
    {
     "expr": "engine_daemon_container_states_containers{job=\"worker-2\", state=\"stopped\"}",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Container CPU Backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * rate(container_cpu_usage_seconds_total{job=\"backend\", name=~\".+\"}[1m]) / on(instance) group_left(container_name) machine_cpu_cores{job=\"backend\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Mem Backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{job=\"backend\", name=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container CPU Worker 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * rate(container_cpu_usage_seconds_total{job=\"worker-1\", name=~\".+\"}[1m]) / on(instance) group_left(container_name) machine_cpu_cores{job=\"worker-1\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Mem Worker 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{job=\"worker-1\", name=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container CPU Worker 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * rate(container_cpu_usage_seconds_total{job=\"worker-2\", name=~\".+\"}[1m]) / on(instance) group_left(container_name) machine_cpu_cores{job=\"worker-2\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Mem Worker 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{job=\"worker-2\", name=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "I/O Backend",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(container_fs_io_time_seconds_total{job=\"backend\", name=~\".+\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "I/O Worker 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(container_fs_io_time_seconds_total{job=\"worker-1\", name=~\".+\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "I/O Worker 2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(container_fs_io_time_seconds_total{job=\"worker-2\", name=~\".+\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Network Backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{job=\"backend\", name=~\".+\"}[1m])) by (name)",
     "legendFormat": "{{name}} sent"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{job=\"backend\", name=~\".+\"}[1m])) by (name)",
     "legendFormat": "{{name}} receive"
    }
   ]
  },
  {
   "title": "Container Network Worker 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{job=\"worker-1\", name=~\".+\"}[1m])) by (name)",
     "legendFormat": "{{name}} sent"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{job=\"worker-1\", name=~\".+\"}[1m])) by (name)",
     "legendFormat": "{{name}} receive"
    }
   ]
  },
  {
   "title": "Container Network Worker 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{job=\"worker-2\", name=~\".+\"}[1m])) by (name)",
     "legendFormat": "{{name}} sent"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{job=\"worker-2\", name=~\".+\"}[1m])) by (name)",
     "legendFormat": "{{name}} receive"
    }
   ]
  }
 ]
}