name: Test
on:
  push:
    branches:
      - main 
  pull_request:
jobs:
  test:
    name: test-and-coverage
    runs-on: ubuntu-latest
    permissions:
      # Required: allow read access to the content for analysis.
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
      - name: generate test coverage
        run: go test ./lib/... -coverprofile=./profile.cov -covermode=atomic