name: test
on: [push]
permissions:
  contents: write
jobs:
  test:
    name: Go test and coverage check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      
      - name: generate test coverage
        run: go test ./lib/... -coverprofile=./profile.cov -covermode=atomic

      # see for badges: https://github.com/vladopajic/go-test-coverage/blob/main/docs/badge.md
      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yml
          ## when token is not specified (value '') this feature is turend off
          ## in this example badge is created and committed only for main brach
          git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
          ## name of branch where badges are stored
          ## ideally this should be orphan branch (see below how to create this branch)
          git-branch: badges 