name: test
on: [push]
permissions:
  contents: write
jobs:
  test:
    name: Go test and coverage check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      
      - name: generate test coverage
        run: go test ./lib/... -coverprofile=./profile.cov -covermode=atomic

      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yml